import "./output.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="bg-base-200">
			<body>
				<Navbar />
				<div>{children}</div>
				<Footer />
			</body>
		</html>
	);
}
